# Brownie configuration for Green Hydrogen Credit System

project_structure:
    build: build
    contracts: contracts
    interfaces: interfaces
    reports: reports
    scripts: scripts
    tests: tests

networks:
    development:
        host: http://127.0.0.1:8545
        gas_limit: 6721975
        gas_buffer: 1.1
        gas_price: 20000000000
        max_fee: null
        priority_fee: null
        reverting_tx_gas_limit: false
        default_contract_owner: true
        cmd_settings:
            port: 8545
            gas_limit: 6721975
            accounts: 10
            evm_version: istanbul
            mnemonic: brownie
            block_time: 0
            default_balance: 100

dependencies:
    - OpenZeppelin/openzeppelin-contracts@4.8.0

compiler:
    solc:
        version: 0.8.19
        optimizer:
            enabled: true
            runs: 200
        remappings:
            - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.0"

console:
    show_colors: true
    auto_suggest: true

reports:
    exclude_contracts:
        - SafeMath

hypothesis:
    deadline: null
    max_examples: 50
    report_multiple_bugs: False
    stateful_step_count: 10
    phases:
        explicit: 30
        reuse: 10
        generate: 40
        target: 40
        shrink: 20